const FOLDER_CLEAR = 'FOLDER_CLEAR';
const FOLDER_SET_CHILDREN = 'FOLDER_SET_CHILDREN';
const FOLDER_CLEAR_CHILDREN = 'FOLDER_CLEAR_CHILDREN';
const FOLDER_SET_ROOT_ID = 'FOLDER_SET_ROOT_ID';

const FOLDER_ENTER = 'FOLDER_ENTER';
const FOLDER_BACK = 'FOLDER_BACK'
const FOLDER_CHANGE_COLOR = 'FOLDER_CHANGE_COLOR'
const FOLDER_DELETE = 'FOLDER_DELETE'
const FOLDER_SET_NAME = 'FOLDER_SET_NAME'
const FOLDER_SET_PERMISSION = 'FOLDER_SET_PERMISSION'

const FOLDER_SELECT = 'FOLDER_SELECT'
const FOLDER_UNSELECT = 'FOLDER_UNSELECT'
const FOLDER_SELECT_CLEAR = 'FOLDER_SELECT_CLEAR'

const folderOperations = {
    FOLDER_CLEAR,
    FOLDER_SET_CHILDREN,
    FOLDER_CLEAR_CHILDREN,
    FOLDER_SET_ROOT_ID,
    FOLDER_SELECT,
    FOLDER_ENTER,
    FOLDER_BACK,
    FOLDER_CHANGE_COLOR,
    FOLDER_DELETE,
    FOLDER_SET_NAME,
    FOLDER_SET_PERMISSION,
    FOLDER_UNSELECT,
    FOLDER_SELECT_CLEAR
}

export default folderOperations
