const FOLDER_CLEAR = 'FOLDER_CLEAR';
const FOLDER_SET_CHILDREN = 'FOLDER_SET_CHILDREN';
const FOLDER_CLEAR_CHILDREN = 'FOLDER_CLEAR_CHILDREN';
const FOLDER_SET_ROOT_ID = 'FOLDER_SET_ROOT_ID';
const FOLDER_SELECT = 'FOLDER_SELECT'

const folderOperations = {
    FOLDER_CLEAR,
    FOLDER_SET_CHILDREN,
    FOLDER_CLEAR_CHILDREN,
    FOLDER_SET_ROOT_ID,
    FOLDER_SELECT
}

export default folderOperations
